# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /csszfs

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: localhost
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.css.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: 1 #逻辑已删除值默认1
      logic-not-delete-value: 0  #逻辑未删除值默认0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


csscva:
  redis:
    open: false
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5[www.css.com]
    # token有效时长，一小时，单位秒
    expire: 3600
    header: token

sso:
  url: http://10.13.16.196:8086/baseSSOzwww/ssoCheck.action?toUrl=http://10.13.16.167:8080/               #单点登录url
  #url: http://10.13.20.5:6003/baseSSOzwww/ssoCheck.action?toUrl=http://10.13.1.254:8080/               #单点登录url
  #url: http://10.13.20.5:6003/baseSSOzwww/ssoCheck.action?toUrl=http://192.168.100.114:8083/               #单点登录url
  #url: http://10.13.20.5:6003/baseSSOzwww/ssoCheck.action?toUrl=http://10.13.1.222:8081/               #单点登录url
  #url: http://10.13.20.5:6003/baseSSOzwww/ssoCheck.action?toUrl=http://127.0.0.1:8083/               #单点登录url
  #url: http://10.13.20.5:6003/baseSSOzwww/ssoCheck.action?toUrl=http://192.168.79.131:8090/               #单点登录url
  #url: http://10.13.20.5:6003/baseSSOzwww/ssoCheck.action?toUrl=http://10.13.111.1:8090/               #单点登录url
  #getUserByUserId: http://10.13.20.5:6005/microservice/api/suser/getUser?userId=        #获取用户url
  getUserByUserId: http://10.13.16.196:8086/microservice/api/suser/getUser?userId=        #获取用户url
  #getMenu: http://10.13.20.5:6005/microservice/api/smenu/listMenus                      #获取menu
  getMenu: http://10.13.16.196:8086/microservice/api/smenu/listMenus                      #获取menu
  #funcUrl: http://10.13.20.5:6005/microservice/api/sfunc/listFuncsByUser                #获取功能列表
  funcUrl: http://10.13.16.196:8086/microservice/api/sfunc/listFuncsByUser                #获取功能列表
  dictListByTableUrl: http://10.13.20.5:6005/microservice/api/sdict/queryDictListByTable?table=    #根据字典表名获取字典列表
  dictsByDictCodeUrl: http://10.13.20.5:6005/microservice/api/sdict/getDictsByDictCode?parentCode=   #根据字典编码，父节点编码，查询子集字典项
  rl: http://192.168.23.51:6888/area/areas/queryByParentId?isAll=0&parentId=1  #查询全国所有的省
  cl: http://192.168.23.51:6888/area/areas/queryByParentId?isAll=0&parentId=       #查询某个省下的所有市
  #quitUrl: http://10.13.20.5:6003/baseSSOzwww/quit.action?toUrl=http://10.13.16.114:8083/     #查询某个省下的所有市
  quitUrl: http://10.13.16.196:8086/baseSSOzwww/quit.action?toUrl=http://10.13.16.167:8080   #查询某个省下的所有市
  pushMessageUrl: http://10.13.20.5:6005/microservice/api/smsgcenter/pushMessage #发邮件、短息url
  messageTypeUrl: http://10.13.20.5:6006/slwcssmsgcenter/rest/smsgcenter/getMsgType?appCode=MessageTypeUrl #发邮件、短息url
  queryCompany: http://10.13.20.5:6005/microservice/api/InternetUserApi/queryCompany    #通过统一信用代码获取主体信息
  sendMessageCenter: http://10.13.20.5:6005/microservice/api/InternetUserApi/sendMessageCenter    #发送门户消息
  roleByUserId: http://10.13.20.5:6005/microservice/api/suser/getRoleByUserId?userId=
  sysId: '1234'
  sysName: '执法监督系统'