
CREATE TABLE "CSSCVA"."QRTZ_BLOB_TRIGGERS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"TRIGGER_NAME" VARCHAR(600) NOT NULL,
"TRIGGER_GROUP" VARCHAR(600) NOT NULL,
"BLOB_DATA" BLOB,
CONSTRAINT "PRIMARY" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "qrtz_blob_triggers_ibfk_1" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "SCHED_NAME" ON "CSSCVA"."QRTZ_BLOB_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_CALENDARS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"CALENDAR_NAME" VARCHAR(600) NOT NULL,
"CALENDAR" BLOB NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "CALENDAR_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_CRON_TRIGGERS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"TRIGGER_NAME" VARCHAR(600) NOT NULL,
"TRIGGER_GROUP" VARCHAR(600) NOT NULL,
"CRON_EXPRESSION" VARCHAR(360) NOT NULL,
"TIME_ZONE_ID" VARCHAR(240),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "qrtz_cron_triggers_ibfk_1" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_FIRED_TRIGGERS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"ENTRY_ID" VARCHAR(285) NOT NULL,
"TRIGGER_NAME" VARCHAR(600) NOT NULL,
"TRIGGER_GROUP" VARCHAR(600) NOT NULL,
"INSTANCE_NAME" VARCHAR(600) NOT NULL,
"FIRED_TIME" BIGINT NOT NULL,
"SCHED_TIME" BIGINT NOT NULL,
"PRIORITY" INT NOT NULL,
"STATE" VARCHAR(48) NOT NULL,
"JOB_NAME" VARCHAR(600),
"JOB_GROUP" VARCHAR(600),
"IS_NONCONCURRENT" VARCHAR(3),
"REQUESTS_RECOVERY" VARCHAR(3),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "ENTRY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_INST_JOB_REQ_RCVRY" ON "CSSCVA"."QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"INSTANCE_NAME" ASC,"REQUESTS_RECOVERY" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_J_G" ON "CSSCVA"."QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"JOB_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_JG" ON "CSSCVA"."QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_T_G" ON "CSSCVA"."QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_TG" ON "CSSCVA"."QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_TRIG_INST_NAME" ON "CSSCVA"."QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"INSTANCE_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_JOB_DETAILS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"JOB_NAME" VARCHAR(600) NOT NULL,
"JOB_GROUP" VARCHAR(600) NOT NULL,
"DESCRIPTION" VARCHAR(750),
"JOB_CLASS_NAME" VARCHAR(750) NOT NULL,
"IS_DURABLE" VARCHAR(3) NOT NULL,
"IS_NONCONCURRENT" VARCHAR(3) NOT NULL,
"IS_UPDATE_DATA" VARCHAR(3) NOT NULL,
"REQUESTS_RECOVERY" VARCHAR(3) NOT NULL,
"JOB_DATA" BLOB,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_J_GRP" ON "CSSCVA"."QRTZ_JOB_DETAILS"("SCHED_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_J_REQ_RECOVERY" ON "CSSCVA"."QRTZ_JOB_DETAILS"("SCHED_NAME" ASC,"REQUESTS_RECOVERY" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_LOCKS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"LOCK_NAME" VARCHAR(120) NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "LOCK_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_PAUSED_TRIGGER_GRPS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"TRIGGER_GROUP" VARCHAR(600) NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_SCHEDULER_STATE"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"INSTANCE_NAME" VARCHAR(600) NOT NULL,
"LAST_CHECKIN_TIME" BIGINT NOT NULL,
"CHECKIN_INTERVAL" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "INSTANCE_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_SIMPLE_TRIGGERS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"TRIGGER_NAME" VARCHAR(600) NOT NULL,
"TRIGGER_GROUP" VARCHAR(600) NOT NULL,
"REPEAT_COUNT" BIGINT NOT NULL,
"REPEAT_INTERVAL" BIGINT NOT NULL,
"TIMES_TRIGGERED" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "qrtz_simple_triggers_ibfk_1" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_SIMPROP_TRIGGERS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"TRIGGER_NAME" VARCHAR(600) NOT NULL,
"TRIGGER_GROUP" VARCHAR(600) NOT NULL,
"STR_PROP_1" VARCHAR(1536),
"STR_PROP_2" VARCHAR(1536),
"STR_PROP_3" VARCHAR(1536),
"INT_PROP_1" INT,
"INT_PROP_2" INT,
"LONG_PROP_1" BIGINT,
"LONG_PROP_2" BIGINT,
"DEC_PROP_1" DECIMAL(13,4),
"DEC_PROP_2" DECIMAL(13,4),
"BOOL_PROP_1" VARCHAR(3),
"BOOL_PROP_2" VARCHAR(3),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "qrtz_simprop_triggers_ibfk_1" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."QRTZ_TRIGGERS"
(
"SCHED_NAME" VARCHAR(360) NOT NULL,
"TRIGGER_NAME" VARCHAR(600) NOT NULL,
"TRIGGER_GROUP" VARCHAR(600) NOT NULL,
"JOB_NAME" VARCHAR(600) NOT NULL,
"JOB_GROUP" VARCHAR(600) NOT NULL,
"DESCRIPTION" VARCHAR(750),
"NEXT_FIRE_TIME" BIGINT,
"PREV_FIRE_TIME" BIGINT,
"PRIORITY" INT,
"TRIGGER_STATE" VARCHAR(48) NOT NULL,
"TRIGGER_TYPE" VARCHAR(24) NOT NULL,
"START_TIME" BIGINT NOT NULL,
"END_TIME" BIGINT,
"CALENDAR_NAME" VARCHAR(600),
"MISFIRE_INSTR" SMALLINT,
"JOB_DATA" BLOB,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "qrtz_triggers_ibfk_1" FOREIGN KEY("SCHED_NAME", "JOB_NAME", "JOB_GROUP") REFERENCES "CSSCVA"."QRTZ_JOB_DETAILS"("SCHED_NAME", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_C" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"CALENDAR_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_G" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_J" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"JOB_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_JG" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_N_G_STATE" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_GROUP" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_N_STATE" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NEXT_FIRE_TIME" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"NEXT_FIRE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NFT_MISFIRE" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"MISFIRE_INSTR" ASC,"NEXT_FIRE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NFT_ST" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_STATE" ASC,"NEXT_FIRE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NFT_ST_MISFIRE" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"MISFIRE_INSTR" ASC,"NEXT_FIRE_TIME" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NFT_ST_MISFIRE_GRP" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"MISFIRE_INSTR" ASC,"NEXT_FIRE_TIME" ASC,"TRIGGER_GROUP" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_STATE" ON "CSSCVA"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "CSSCVA"."SCHEDULE_JOB"
(
"JOB_ID" BIGINT IDENTITY(2, 1) NOT NULL,
"BEAN_NAME" VARCHAR(800),
"PARAMS" VARCHAR(3900),
"CRON_EXPRESSION" VARCHAR(400),
"STATUS" TINYINT,
"REMARK" VARCHAR(1020),
"CREATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("JOB_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SCHEDULE_JOB" IS '定时任务';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB"."JOB_ID" IS '任务id';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB"."BEAN_NAME" IS 'spring bean名称';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB"."PARAMS" IS '参数';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB"."CRON_EXPRESSION" IS 'cron表达式';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB"."STATUS" IS '任务状态  0：正常  1：暂停';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB"."REMARK" IS '备注';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB"."CREATE_TIME" IS '创建时间';


CREATE TABLE "CSSCVA"."SCHEDULE_JOB_LOG"
(
"LOG_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"JOB_ID" BIGINT NOT NULL,
"BEAN_NAME" VARCHAR(800),
"PARAMS" VARCHAR(3900),
"STATUS" TINYINT NOT NULL,
"ERROR" VARCHAR(3900),
"TIMES" INT NOT NULL,
"CREATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("LOG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "JOB_ID" ON "CSSCVA"."SCHEDULE_JOB_LOG"("JOB_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SCHEDULE_JOB_LOG" IS '定时任务日志';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB_LOG"."LOG_ID" IS '任务日志id';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB_LOG"."JOB_ID" IS '任务id';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB_LOG"."BEAN_NAME" IS 'spring bean名称';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB_LOG"."PARAMS" IS '参数';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB_LOG"."STATUS" IS '任务状态    0：成功    1：失败';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB_LOG"."ERROR" IS '失败信息';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB_LOG"."TIMES" IS '耗时(单位：毫秒)';
COMMENT ON COLUMN "CSSCVA"."SCHEDULE_JOB_LOG"."CREATE_TIME" IS '创建时间';


CREATE TABLE "CSSCVA"."SYS_CAPTCHA"
(
"UUID" CHAR(144) NOT NULL,
"CODE" VARCHAR(24) NOT NULL,
"EXPIRE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("UUID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_CAPTCHA" IS '系统验证码';
COMMENT ON COLUMN "CSSCVA"."SYS_CAPTCHA"."UUID" IS 'uuid';
COMMENT ON COLUMN "CSSCVA"."SYS_CAPTCHA"."CODE" IS '验证码';
COMMENT ON COLUMN "CSSCVA"."SYS_CAPTCHA"."EXPIRE_TIME" IS '过期时间';


CREATE TABLE "CSSCVA"."SYS_CONFIG"
(
"ID" BIGINT IDENTITY(2, 1) NOT NULL,
"PARAM_KEY" VARCHAR(200),
"PARAM_VALUE" VARCHAR(3900),
"STATUS" TINYINT DEFAULT 1,
"REMARK" VARCHAR(2000),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "PARAM_KEY" UNIQUE("PARAM_KEY")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_CONFIG" IS '系统配置信息表';
COMMENT ON COLUMN "CSSCVA"."SYS_CONFIG"."PARAM_KEY" IS 'key';
COMMENT ON COLUMN "CSSCVA"."SYS_CONFIG"."PARAM_VALUE" IS 'value';
COMMENT ON COLUMN "CSSCVA"."SYS_CONFIG"."STATUS" IS '状态   0：隐藏   1：显示';
COMMENT ON COLUMN "CSSCVA"."SYS_CONFIG"."REMARK" IS '备注';


CREATE TABLE "CSSCVA"."SYS_LOG"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"USERNAME" VARCHAR(200),
"OPERATION" VARCHAR(200),
"METHOD" VARCHAR(800),
"PARAMS" VARCHAR(3900),
"TIME" BIGINT NOT NULL,
"IP" VARCHAR(256),
"CREATE_DATE" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_LOG" IS '系统日志';
COMMENT ON COLUMN "CSSCVA"."SYS_LOG"."USERNAME" IS '用户名';
COMMENT ON COLUMN "CSSCVA"."SYS_LOG"."OPERATION" IS '用户操作';
COMMENT ON COLUMN "CSSCVA"."SYS_LOG"."METHOD" IS '请求方法';
COMMENT ON COLUMN "CSSCVA"."SYS_LOG"."PARAMS" IS '请求参数';
COMMENT ON COLUMN "CSSCVA"."SYS_LOG"."TIME" IS '执行时长(毫秒)';
COMMENT ON COLUMN "CSSCVA"."SYS_LOG"."IP" IS 'IP地址';
COMMENT ON COLUMN "CSSCVA"."SYS_LOG"."CREATE_DATE" IS '创建时间';


CREATE TABLE "CSSCVA"."SYS_MENU"
(
"MENU_ID" BIGINT IDENTITY(31, 1) NOT NULL,
"PARENT_ID" BIGINT,
"NAME" VARCHAR(200),
"URL" VARCHAR(800),
"PERMS" VARCHAR(2000),
"TYPE" INT,
"ICON" VARCHAR(200),
"ORDER_NUM" INT,
NOT CLUSTER PRIMARY KEY("MENU_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_MENU" IS '菜单管理';
COMMENT ON COLUMN "CSSCVA"."SYS_MENU"."PARENT_ID" IS '父菜单ID，一级菜单为0';
COMMENT ON COLUMN "CSSCVA"."SYS_MENU"."NAME" IS '菜单名称';
COMMENT ON COLUMN "CSSCVA"."SYS_MENU"."URL" IS '菜单URL';
COMMENT ON COLUMN "CSSCVA"."SYS_MENU"."PERMS" IS '授权(多个用逗号分隔，如：user:list,user:create)';
COMMENT ON COLUMN "CSSCVA"."SYS_MENU"."TYPE" IS '类型   0：目录   1：菜单   2：按钮';
COMMENT ON COLUMN "CSSCVA"."SYS_MENU"."ICON" IS '菜单图标';
COMMENT ON COLUMN "CSSCVA"."SYS_MENU"."ORDER_NUM" IS '排序';


CREATE TABLE "CSSCVA"."SYS_OSS"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"URL" VARCHAR(800),
"CREATE_DATE" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_OSS" IS '文件上传';
COMMENT ON COLUMN "CSSCVA"."SYS_OSS"."URL" IS 'URL地址';
COMMENT ON COLUMN "CSSCVA"."SYS_OSS"."CREATE_DATE" IS '创建时间';


CREATE TABLE "CSSCVA"."SYS_ROLE"
(
"ROLE_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"ROLE_NAME" VARCHAR(400),
"REMARK" VARCHAR(400),
"CREATE_USER_ID" BIGINT,
"CREATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_ROLE" IS '角色';
COMMENT ON COLUMN "CSSCVA"."SYS_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "CSSCVA"."SYS_ROLE"."REMARK" IS '备注';
COMMENT ON COLUMN "CSSCVA"."SYS_ROLE"."CREATE_USER_ID" IS '创建者ID';
COMMENT ON COLUMN "CSSCVA"."SYS_ROLE"."CREATE_TIME" IS '创建时间';


CREATE TABLE "CSSCVA"."SYS_ROLE_MENU"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"ROLE_ID" BIGINT,
"MENU_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_ROLE_MENU" IS '角色与菜单对应关系';
COMMENT ON COLUMN "CSSCVA"."SYS_ROLE_MENU"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "CSSCVA"."SYS_ROLE_MENU"."MENU_ID" IS '菜单ID';


CREATE TABLE "CSSCVA"."SYS_USER"
(
"USER_ID" BIGINT IDENTITY(2, 1) NOT NULL,
"USERNAME" VARCHAR(200) NOT NULL,
"PASSWORD" VARCHAR(400),
"SALT" VARCHAR(80),
"EMAIL" VARCHAR(400),
"MOBILE" VARCHAR(400),
"STATUS" TINYINT,
"CREATE_USER_ID" BIGINT,
"CREATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("USER_ID"),
CONSTRAINT "USERNAME" UNIQUE("USERNAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_USER" IS '系统用户';
COMMENT ON COLUMN "CSSCVA"."SYS_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "CSSCVA"."SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "CSSCVA"."SYS_USER"."SALT" IS '盐';
COMMENT ON COLUMN "CSSCVA"."SYS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "CSSCVA"."SYS_USER"."MOBILE" IS '手机号';
COMMENT ON COLUMN "CSSCVA"."SYS_USER"."STATUS" IS '状态  0：禁用   1：正常';
COMMENT ON COLUMN "CSSCVA"."SYS_USER"."CREATE_USER_ID" IS '创建者ID';
COMMENT ON COLUMN "CSSCVA"."SYS_USER"."CREATE_TIME" IS '创建时间';


CREATE TABLE "CSSCVA"."SYS_USER_ROLE"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"USER_ID" BIGINT,
"ROLE_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_USER_ROLE" IS '用户与角色对应关系';
COMMENT ON COLUMN "CSSCVA"."SYS_USER_ROLE"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "CSSCVA"."SYS_USER_ROLE"."ROLE_ID" IS '角色ID';


CREATE TABLE "CSSCVA"."SYS_USER_TOKEN"
(
"USER_ID" BIGINT NOT NULL,
"TOKEN" VARCHAR(400) NOT NULL,
"EXPIRE_TIME" TIMESTAMP(0),
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("USER_ID"),
CONSTRAINT "TOKEN" UNIQUE("TOKEN")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."SYS_USER_TOKEN" IS '系统用户Token';
COMMENT ON COLUMN "CSSCVA"."SYS_USER_TOKEN"."TOKEN" IS 'token';
COMMENT ON COLUMN "CSSCVA"."SYS_USER_TOKEN"."EXPIRE_TIME" IS '过期时间';
COMMENT ON COLUMN "CSSCVA"."SYS_USER_TOKEN"."UPDATE_TIME" IS '更新时间';


CREATE TABLE "CSSCVA"."TB_USER"
(
"USER_ID" BIGINT IDENTITY(2, 1) NOT NULL,
"USERNAME" VARCHAR(200) NOT NULL,
"MOBILE" VARCHAR(80) NOT NULL,
"PASSWORD" VARCHAR(256),
"CREATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("USER_ID"),
UNIQUE("USERNAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "CSSCVA"."TB_USER" IS '用户';
COMMENT ON COLUMN "CSSCVA"."TB_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "CSSCVA"."TB_USER"."MOBILE" IS '手机号';
COMMENT ON COLUMN "CSSCVA"."TB_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "CSSCVA"."TB_USER"."CREATE_TIME" IS '创建时间';


